version: "3.1"

networks:
  Pro290_network:
    external: false

services:

  Traefik:
    image: traefik:latest
    container_name: traefik
    command:
        - '--api.insecure=true'
        - '--providers.consulcatalog=true'
        - '--providers.consulcatalog.prefix=traefik'
        - '--providers.consulcatalog.endpoint.address=consul:8500'
        - '--serversTransport.insecureSkipVerify=true'
        - '--entryPoints.web.address=:80'
        - '--entryPoints.developer_api.address=:8081'
        - '--log.level=DEBUG'
    ports:
      - 80:80
      - 8081:8081
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - ./traefik.yaml:/etc/traefik/traefik.yaml
    networks:
      - Pro290_network
    restart: always

  MongoDBPosts:
    container_name: MongoDBPosts
    image: mongo:latest
    restart: always
    hostname: MongoDBPosts
    ports:
      - "27017:27017"
    networks:
      - Pro290_network

  PostService:
    container_name: postservice
    build: ./postservicejs
    image: postservice:latest
    networks:
      - Pro290_network
    ports:
      - "6001:8080"
    depends_on:
      - MongoDBPosts
      - Consul
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.postservice.rule=Host(`postservice.localhost`)"
    #   - "traefik.http.services.postservice.loadbalancer.server.port=8080"

  Consul:
    image: hashicorp/consul:1.12.0
    container_name: consul
    command: "agent -dev -client=0.0.0.0"
    ports:
      - "8500:8500"
    networks:
      - Pro290_network
    labels:
      - 'traefik.enable=true'
      - 'traefik.consulcatalog.connect=true'
    restart: unless-stopped

  UserService:
    image: user_service:latest
    build:
      context: ./user_service
      dockerfile: /dockerfile
    environment:
      - API_ADDRESS=0.0.0.0
      - USER_URL=postgres://David:Password123@userdatabase:5432/users
      - IMAGE_URL=postgres://David:Password123@imagedatabase:5432/images
      - SECRET_KEY=idkmanwhatdoyouwantfromme
    networks:
      - Pro290_network
    depends_on:
      - Consul

  UserDatabase:
    image: postgres
    container_name: userdatabase
    hostname: userdatabase
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: David
      POSTGRES_PASSWORD: Password123
      POSTGRES_DB: users
    networks:
      - Pro290_network

  ImageDatabase:
    image: postgres
    container_name: imagedatabase
    hostname: imagedatabase
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: David
      POSTGRES_PASSWORD: Password123
      POSTGRES_DB: images
    networks:
      - Pro290_network