name: frontend
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  http: ^0.13.3
  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  file_picker: ^4.0.0
  geolocator: ^12.0.0
  dart_jsonwebtoken: ^2.14.0
  mongo_dart: ^0.10.2
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

assets:
  - asset/images/  